[better-dev] Add tools for better developer experience
elo7/ajax-amd pull request #25
Opened 2020-03-09 15:17 UTC by luiz

Adds terser for automatic code minification and eslint for automatic code standards enforcement.

:warning: Better if updated and merged after #22 :warning:

2020-10-05 15:13 UTC, jeeanribeiro requested changes
Só tive um problema com o linter, ele reclamou que as variáveis Atomics, Int32Array e SharedArrayBuffer não estavam declaradas, acho que vale a pena colocá-las no global do .eslintrc ou adicionar os envs relacionados.

2020-10-05 15:13 UTC, jeeanribeiro commented on test/helpers.js
> +};
Podemos remover esses comentários? :eyes:

2020-11-30 18:06 UTC, luiz commented on test/helpers.js
> +};
Por que remover? Eles vieram com o código original copiado do StackOverflow e explicam o funcionamento do código.

2021-02-01 12:14 UTC, jeeanribeiro approved these changes
:rocket:

2021-02-01 14:20 UTC, thiagocorbalan approved these changes

2021-02-01 14:22 UTC, merged